import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import '../globals.css';
import NextAuthSessionProvider from "@/app/provider/sessionProvider";
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions)
  
  if (session) {
    console.log(session)
    redirect("/importacao")
  }
  return (
    <html lang="en">
      < body className={inter.className} >

        {children}
      </body >
    </html>
  );
}
