import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { nextAuthOptions } from "../api/auth/[...nextauth]/route";
import Navbar from "../components/Navbar";
import '../globals.css'
import { useSession } from "next-auth/react";
import NextAuthSessionProvider from "../provider/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const session = await getServerSession(nextAuthOptions)

  if (!session) {

    redirect("/")
  }
  return (
    <html>

      <body>
        <NextAuthSessionProvider>
          <div className="flex flex-col min-h-screen">

            <Navbar />
            {/* <main className="flex-grow mx-auto w-11/12 h-full  flex-col p-10 self-center rounded-md mt-4"> */}
            <main className="flex-grow mx-auto w-11/12 h-full flex-col p-[5%] md:p-10 self-center rounded-md mt-4"
            >
              {children}
            </main>
          </div>

        </NextAuthSessionProvider>
      </body>

    </html >
  );
}
