import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import '../globals.css';
import NextAuthSessionProvider from "@/app/provider/sessionProvider";
import { getServerSession } from "next-auth";
import { authOptions as nextAuthOptions } from "@/libs/authOptions";

import { redirect } from "next/navigation";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transactix",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions)

  if (session) {
    console.log(session)
    redirect("/importacao")
  }
  return (
    <html lang="en">
      < body className={inter.className} >

        {children}

        <ToastContainer />
      </body >
    </html>
  );
}
